server:
  port: 8082

spring:
  kafka:
    bootstrap-servers: "localhost:9092"
    topics:
      topic-name: event.create.customer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    properties:
      schema:
        registry:
          url: http://0.0.0.0:8081
      specific.avro.reader: true