server:
  port: 8080

spring:
  application:
    name: usermaneger
  datasource:
    url: jdbc:h2:mem:usermanager_db
    username: admin
    password:
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      path: "/h2"
      enable: true

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
  integration:
    producer-event-create-customer: http://localhost:8082