version: '3.1'
services:
  postgres:
    image: postgres
    container_name: emailmanager-container
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - '5432:5432'
    volumes:
      - "./setup/init.sql:/docker-entrypoint-initdb.d/1.sql"

volumes:
  scripts: